controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_index:
    path: /
    controller: App\Controller\IndexController::index

product_single:
    path: /product/{slug}
    controller: App\Controller\IndexController::product