controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_index:
  path: /
  controller: App\Controller\IndexController::index

product_single:
  path: /product/{slug}
  controller: App\Controller\IndexController::product


index_products:
  prefix: '/admin/products'
  path: '/'
  controller: App\Controller\ProductsController::index
  methods: GET

create_products:
  prefix: '/admin/products'
  path: '/create'
  controller: App\Controller\ProductsController::create
  methods: GET

store_products:
  prefix: '/admin/products'
  path: '/store'
  controller: App\Controller\ProductsController::store
  methods: POST

edit_products:
  prefix: '/admin/products'
  path: '/edit/{product}'
  controller: App\Controller\ProductsController::edit
  methods: GET

update_products:
  prefix: '/admin/products'
  path: '/update/{product}'
  controller: App\Controller\ProductsController::update
  methods: PUT

remove_products:
  prefix: '/admin/products'
  path: '/remove/{product}'
  controller: App\Controller\ProductsController::remove
  methods: DELETE